name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore ./Chirp.Razor/Chirp.Razor.csproj
    - name: Build
      run: dotnet build ./Chirp.Razor/Chirp.Razor.csproj --no-restore
    - name: Run API Tests
      run: dotnet test ./test/Chirp.ApiTests/Chirp.ApiTests.csproj --no-build --verbosity normal
    - name: Run E2E Tests
      run: dotnet test ./test/Chirp.E2ETest/Chirp.E2ETest.csproj --no-build --verbosity normal
    - name: Run Integration Tests
      run: dotnet test ./test/integration/integration.csproj --no-build --verbosity normal
    - name: Run Unit Tests
      run: dotnet test ./test/unit/unit.csproj --no-build --verbosity normal